// This file is auto-generated by @hey-api/openapi-ts

import { type Options, getProjectsProjectsGet, createProjectProjectsPost, getProjectProjectsProjectIdGet, getTrainSessionsSessionsProjectProjectIdGet, createTrainSessionSessionsProjectProjectIdPost, getTrainSessionSessionsSessionIdGet, updateTrainSessionSessionsSessionIdPatch, getTrainSessionStatusSessionsSessionIdStatusGet, getModelSessionsSessionIdModelGet, registerModelSessionsSessionIdModelPost, getStepsSessionsSessionIdStepGet, registerStepSessionsSessionIdStepPost, createSessionLogSessionsSessionIdLogPost, getSessionLogsSessionsSessionIdLogsGet, runSessionDiagnosticsDiagnosticsSessionsSessionIdRunPost, listSessionDiagnosticRunsDiagnosticsSessionsSessionIdGet, getDiagnosticRunDiagnosticsRunsRunIdGet, getSessionHealthDiagnosticsSessionsSessionIdHealthGet, getProjectTrendDiagnosticsProjectsProjectIdTrendGet } from '../sdk.gen';
import { queryOptions, type UseMutationOptions } from '@tanstack/react-query';
import type { GetProjectsProjectsGetData, CreateProjectProjectsPostData, CreateProjectProjectsPostError, CreateProjectProjectsPostResponse, GetProjectProjectsProjectIdGetData, GetTrainSessionsSessionsProjectProjectIdGetData, CreateTrainSessionSessionsProjectProjectIdPostData, CreateTrainSessionSessionsProjectProjectIdPostError, CreateTrainSessionSessionsProjectProjectIdPostResponse, GetTrainSessionSessionsSessionIdGetData, UpdateTrainSessionSessionsSessionIdPatchData, UpdateTrainSessionSessionsSessionIdPatchError, UpdateTrainSessionSessionsSessionIdPatchResponse, GetTrainSessionStatusSessionsSessionIdStatusGetData, GetModelSessionsSessionIdModelGetData, RegisterModelSessionsSessionIdModelPostData, RegisterModelSessionsSessionIdModelPostError, RegisterModelSessionsSessionIdModelPostResponse, GetStepsSessionsSessionIdStepGetData, RegisterStepSessionsSessionIdStepPostData, RegisterStepSessionsSessionIdStepPostError, RegisterStepSessionsSessionIdStepPostResponse, CreateSessionLogSessionsSessionIdLogPostData, CreateSessionLogSessionsSessionIdLogPostError, CreateSessionLogSessionsSessionIdLogPostResponse, GetSessionLogsSessionsSessionIdLogsGetData, RunSessionDiagnosticsDiagnosticsSessionsSessionIdRunPostData, RunSessionDiagnosticsDiagnosticsSessionsSessionIdRunPostError, RunSessionDiagnosticsDiagnosticsSessionsSessionIdRunPostResponse, ListSessionDiagnosticRunsDiagnosticsSessionsSessionIdGetData, GetDiagnosticRunDiagnosticsRunsRunIdGetData, GetSessionHealthDiagnosticsSessionsSessionIdHealthGetData, GetProjectTrendDiagnosticsProjectsProjectIdTrendGetData } from '../types.gen';
import { client as _heyApiClient } from '../client.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: (options?.client ?? _heyApiClient).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [
        params
    ];
};

export const getProjectsProjectsGetQueryKey = (options?: Options<GetProjectsProjectsGetData>) => createQueryKey('getProjectsProjectsGet', options);

export const getProjectsProjectsGetOptions = (options?: Options<GetProjectsProjectsGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getProjectsProjectsGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getProjectsProjectsGetQueryKey(options)
    });
};

export const createProjectProjectsPostQueryKey = (options: Options<CreateProjectProjectsPostData>) => createQueryKey('createProjectProjectsPost', options);

export const createProjectProjectsPostOptions = (options: Options<CreateProjectProjectsPostData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await createProjectProjectsPost({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: createProjectProjectsPostQueryKey(options)
    });
};

export const createProjectProjectsPostMutation = (options?: Partial<Options<CreateProjectProjectsPostData>>): UseMutationOptions<CreateProjectProjectsPostResponse, CreateProjectProjectsPostError, Options<CreateProjectProjectsPostData>> => {
    const mutationOptions: UseMutationOptions<CreateProjectProjectsPostResponse, CreateProjectProjectsPostError, Options<CreateProjectProjectsPostData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await createProjectProjectsPost({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getProjectProjectsProjectIdGetQueryKey = (options: Options<GetProjectProjectsProjectIdGetData>) => createQueryKey('getProjectProjectsProjectIdGet', options);

export const getProjectProjectsProjectIdGetOptions = (options: Options<GetProjectProjectsProjectIdGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getProjectProjectsProjectIdGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getProjectProjectsProjectIdGetQueryKey(options)
    });
};

export const getTrainSessionsSessionsProjectProjectIdGetQueryKey = (options: Options<GetTrainSessionsSessionsProjectProjectIdGetData>) => createQueryKey('getTrainSessionsSessionsProjectProjectIdGet', options);

export const getTrainSessionsSessionsProjectProjectIdGetOptions = (options: Options<GetTrainSessionsSessionsProjectProjectIdGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getTrainSessionsSessionsProjectProjectIdGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getTrainSessionsSessionsProjectProjectIdGetQueryKey(options)
    });
};

export const createTrainSessionSessionsProjectProjectIdPostQueryKey = (options: Options<CreateTrainSessionSessionsProjectProjectIdPostData>) => createQueryKey('createTrainSessionSessionsProjectProjectIdPost', options);

export const createTrainSessionSessionsProjectProjectIdPostOptions = (options: Options<CreateTrainSessionSessionsProjectProjectIdPostData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await createTrainSessionSessionsProjectProjectIdPost({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: createTrainSessionSessionsProjectProjectIdPostQueryKey(options)
    });
};

export const createTrainSessionSessionsProjectProjectIdPostMutation = (options?: Partial<Options<CreateTrainSessionSessionsProjectProjectIdPostData>>): UseMutationOptions<CreateTrainSessionSessionsProjectProjectIdPostResponse, CreateTrainSessionSessionsProjectProjectIdPostError, Options<CreateTrainSessionSessionsProjectProjectIdPostData>> => {
    const mutationOptions: UseMutationOptions<CreateTrainSessionSessionsProjectProjectIdPostResponse, CreateTrainSessionSessionsProjectProjectIdPostError, Options<CreateTrainSessionSessionsProjectProjectIdPostData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await createTrainSessionSessionsProjectProjectIdPost({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getTrainSessionSessionsSessionIdGetQueryKey = (options: Options<GetTrainSessionSessionsSessionIdGetData>) => createQueryKey('getTrainSessionSessionsSessionIdGet', options);

export const getTrainSessionSessionsSessionIdGetOptions = (options: Options<GetTrainSessionSessionsSessionIdGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getTrainSessionSessionsSessionIdGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getTrainSessionSessionsSessionIdGetQueryKey(options)
    });
};

export const updateTrainSessionSessionsSessionIdPatchMutation = (options?: Partial<Options<UpdateTrainSessionSessionsSessionIdPatchData>>): UseMutationOptions<UpdateTrainSessionSessionsSessionIdPatchResponse, UpdateTrainSessionSessionsSessionIdPatchError, Options<UpdateTrainSessionSessionsSessionIdPatchData>> => {
    const mutationOptions: UseMutationOptions<UpdateTrainSessionSessionsSessionIdPatchResponse, UpdateTrainSessionSessionsSessionIdPatchError, Options<UpdateTrainSessionSessionsSessionIdPatchData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await updateTrainSessionSessionsSessionIdPatch({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getTrainSessionStatusSessionsSessionIdStatusGetQueryKey = (options: Options<GetTrainSessionStatusSessionsSessionIdStatusGetData>) => createQueryKey('getTrainSessionStatusSessionsSessionIdStatusGet', options);

export const getTrainSessionStatusSessionsSessionIdStatusGetOptions = (options: Options<GetTrainSessionStatusSessionsSessionIdStatusGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getTrainSessionStatusSessionsSessionIdStatusGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getTrainSessionStatusSessionsSessionIdStatusGetQueryKey(options)
    });
};

export const getModelSessionsSessionIdModelGetQueryKey = (options: Options<GetModelSessionsSessionIdModelGetData>) => createQueryKey('getModelSessionsSessionIdModelGet', options);

export const getModelSessionsSessionIdModelGetOptions = (options: Options<GetModelSessionsSessionIdModelGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getModelSessionsSessionIdModelGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getModelSessionsSessionIdModelGetQueryKey(options)
    });
};

export const registerModelSessionsSessionIdModelPostQueryKey = (options: Options<RegisterModelSessionsSessionIdModelPostData>) => createQueryKey('registerModelSessionsSessionIdModelPost', options);

export const registerModelSessionsSessionIdModelPostOptions = (options: Options<RegisterModelSessionsSessionIdModelPostData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await registerModelSessionsSessionIdModelPost({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: registerModelSessionsSessionIdModelPostQueryKey(options)
    });
};

export const registerModelSessionsSessionIdModelPostMutation = (options?: Partial<Options<RegisterModelSessionsSessionIdModelPostData>>): UseMutationOptions<RegisterModelSessionsSessionIdModelPostResponse, RegisterModelSessionsSessionIdModelPostError, Options<RegisterModelSessionsSessionIdModelPostData>> => {
    const mutationOptions: UseMutationOptions<RegisterModelSessionsSessionIdModelPostResponse, RegisterModelSessionsSessionIdModelPostError, Options<RegisterModelSessionsSessionIdModelPostData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await registerModelSessionsSessionIdModelPost({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getStepsSessionsSessionIdStepGetQueryKey = (options: Options<GetStepsSessionsSessionIdStepGetData>) => createQueryKey('getStepsSessionsSessionIdStepGet', options);

export const getStepsSessionsSessionIdStepGetOptions = (options: Options<GetStepsSessionsSessionIdStepGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getStepsSessionsSessionIdStepGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getStepsSessionsSessionIdStepGetQueryKey(options)
    });
};

export const registerStepSessionsSessionIdStepPostQueryKey = (options: Options<RegisterStepSessionsSessionIdStepPostData>) => createQueryKey('registerStepSessionsSessionIdStepPost', options);

export const registerStepSessionsSessionIdStepPostOptions = (options: Options<RegisterStepSessionsSessionIdStepPostData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await registerStepSessionsSessionIdStepPost({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: registerStepSessionsSessionIdStepPostQueryKey(options)
    });
};

export const registerStepSessionsSessionIdStepPostMutation = (options?: Partial<Options<RegisterStepSessionsSessionIdStepPostData>>): UseMutationOptions<RegisterStepSessionsSessionIdStepPostResponse, RegisterStepSessionsSessionIdStepPostError, Options<RegisterStepSessionsSessionIdStepPostData>> => {
    const mutationOptions: UseMutationOptions<RegisterStepSessionsSessionIdStepPostResponse, RegisterStepSessionsSessionIdStepPostError, Options<RegisterStepSessionsSessionIdStepPostData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await registerStepSessionsSessionIdStepPost({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const createSessionLogSessionsSessionIdLogPostQueryKey = (options: Options<CreateSessionLogSessionsSessionIdLogPostData>) => createQueryKey('createSessionLogSessionsSessionIdLogPost', options);

export const createSessionLogSessionsSessionIdLogPostOptions = (options: Options<CreateSessionLogSessionsSessionIdLogPostData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await createSessionLogSessionsSessionIdLogPost({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: createSessionLogSessionsSessionIdLogPostQueryKey(options)
    });
};

export const createSessionLogSessionsSessionIdLogPostMutation = (options?: Partial<Options<CreateSessionLogSessionsSessionIdLogPostData>>): UseMutationOptions<CreateSessionLogSessionsSessionIdLogPostResponse, CreateSessionLogSessionsSessionIdLogPostError, Options<CreateSessionLogSessionsSessionIdLogPostData>> => {
    const mutationOptions: UseMutationOptions<CreateSessionLogSessionsSessionIdLogPostResponse, CreateSessionLogSessionsSessionIdLogPostError, Options<CreateSessionLogSessionsSessionIdLogPostData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await createSessionLogSessionsSessionIdLogPost({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getSessionLogsSessionsSessionIdLogsGetQueryKey = (options: Options<GetSessionLogsSessionsSessionIdLogsGetData>) => createQueryKey('getSessionLogsSessionsSessionIdLogsGet', options);

export const getSessionLogsSessionsSessionIdLogsGetOptions = (options: Options<GetSessionLogsSessionsSessionIdLogsGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getSessionLogsSessionsSessionIdLogsGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getSessionLogsSessionsSessionIdLogsGetQueryKey(options)
    });
};

export const runSessionDiagnosticsDiagnosticsSessionsSessionIdRunPostQueryKey = (options: Options<RunSessionDiagnosticsDiagnosticsSessionsSessionIdRunPostData>) => createQueryKey('runSessionDiagnosticsDiagnosticsSessionsSessionIdRunPost', options);

export const runSessionDiagnosticsDiagnosticsSessionsSessionIdRunPostOptions = (options: Options<RunSessionDiagnosticsDiagnosticsSessionsSessionIdRunPostData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await runSessionDiagnosticsDiagnosticsSessionsSessionIdRunPost({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: runSessionDiagnosticsDiagnosticsSessionsSessionIdRunPostQueryKey(options)
    });
};

export const runSessionDiagnosticsDiagnosticsSessionsSessionIdRunPostMutation = (options?: Partial<Options<RunSessionDiagnosticsDiagnosticsSessionsSessionIdRunPostData>>): UseMutationOptions<RunSessionDiagnosticsDiagnosticsSessionsSessionIdRunPostResponse, RunSessionDiagnosticsDiagnosticsSessionsSessionIdRunPostError, Options<RunSessionDiagnosticsDiagnosticsSessionsSessionIdRunPostData>> => {
    const mutationOptions: UseMutationOptions<RunSessionDiagnosticsDiagnosticsSessionsSessionIdRunPostResponse, RunSessionDiagnosticsDiagnosticsSessionsSessionIdRunPostError, Options<RunSessionDiagnosticsDiagnosticsSessionsSessionIdRunPostData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await runSessionDiagnosticsDiagnosticsSessionsSessionIdRunPost({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const listSessionDiagnosticRunsDiagnosticsSessionsSessionIdGetQueryKey = (options: Options<ListSessionDiagnosticRunsDiagnosticsSessionsSessionIdGetData>) => createQueryKey('listSessionDiagnosticRunsDiagnosticsSessionsSessionIdGet', options);

export const listSessionDiagnosticRunsDiagnosticsSessionsSessionIdGetOptions = (options: Options<ListSessionDiagnosticRunsDiagnosticsSessionsSessionIdGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await listSessionDiagnosticRunsDiagnosticsSessionsSessionIdGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: listSessionDiagnosticRunsDiagnosticsSessionsSessionIdGetQueryKey(options)
    });
};

export const getDiagnosticRunDiagnosticsRunsRunIdGetQueryKey = (options: Options<GetDiagnosticRunDiagnosticsRunsRunIdGetData>) => createQueryKey('getDiagnosticRunDiagnosticsRunsRunIdGet', options);

export const getDiagnosticRunDiagnosticsRunsRunIdGetOptions = (options: Options<GetDiagnosticRunDiagnosticsRunsRunIdGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getDiagnosticRunDiagnosticsRunsRunIdGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getDiagnosticRunDiagnosticsRunsRunIdGetQueryKey(options)
    });
};

export const getSessionHealthDiagnosticsSessionsSessionIdHealthGetQueryKey = (options: Options<GetSessionHealthDiagnosticsSessionsSessionIdHealthGetData>) => createQueryKey('getSessionHealthDiagnosticsSessionsSessionIdHealthGet', options);

export const getSessionHealthDiagnosticsSessionsSessionIdHealthGetOptions = (options: Options<GetSessionHealthDiagnosticsSessionsSessionIdHealthGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getSessionHealthDiagnosticsSessionsSessionIdHealthGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getSessionHealthDiagnosticsSessionsSessionIdHealthGetQueryKey(options)
    });
};

export const getProjectTrendDiagnosticsProjectsProjectIdTrendGetQueryKey = (options: Options<GetProjectTrendDiagnosticsProjectsProjectIdTrendGetData>) => createQueryKey('getProjectTrendDiagnosticsProjectsProjectIdTrendGet', options);

export const getProjectTrendDiagnosticsProjectsProjectIdTrendGetOptions = (options: Options<GetProjectTrendDiagnosticsProjectsProjectIdTrendGetData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await getProjectTrendDiagnosticsProjectsProjectIdTrendGet({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getProjectTrendDiagnosticsProjectsProjectIdTrendGetQueryKey(options)
    });
};