"""Add sustainability columns to trainstep

Revision ID: e57e1f3af050
Revises: a1b2c3d4e5f6
Create Date: 2026-02-21 20:37:24.485839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e57e1f3af050'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainstep', sa.Column('layer_health', sa.JSON(), nullable=True))
    op.add_column('trainstep', sa.Column('sustainability', sa.JSON(), nullable=True))
    op.add_column('trainstep', sa.Column('carbon_emissions', sa.JSON(), nullable=True))
    op.add_column('trainstep', sa.Column('log_counts', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trainstep', 'log_counts')
    op.drop_column('trainstep', 'carbon_emissions')
    op.drop_column('trainstep', 'sustainability')
    op.drop_column('trainstep', 'layer_health')
    # ### end Alembic commands ###
