// This file is auto-generated by @hey-api/openapi-ts

/**
 * Full detail for a single diagnostic run.
 */
export type DiagnosticRunOut = {
    id: number;
    session_id: number;
    created_at: string;
    health_score: number;
    issue_count: number;
    arch_type: string;
    summary_json?: {
        [key: string]: unknown;
    } | null;
    issues: Array<IssueOut>;
    epoch_trends: Array<EpochDiagnosticSummary>;
    session_level_issues: Array<IssueOut>;
    layer_highlights: Array<LayerHighlight>;
    sustainability?: SustainabilityInsight | null;
};

/**
 * Lightweight view returned by the list endpoint.
 */
export type DiagnosticRunSummary = {
    id: number;
    session_id: number;
    created_at: string;
    health_score: number;
    issue_count: number;
    arch_type: string;
    summary_json?: {
        [key: string]: unknown;
    } | null;
};

export type EpochDiagnosticSummary = {
    epoch_index: number;
    issues: Array<IssueOut>;
};

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

export type HealthOut = {
    session_id: number;
    health_score: number;
    severity_counts: {
        [key: string]: number;
    };
    issues: Array<IssueOut>;
    layers: Array<LayerHighlight>;
};

export type IssueCategory = 'loss' | 'throughput' | 'memory' | 'profiler' | 'logs' | 'system' | 'architecture' | 'sustainability';

export type IssueOut = {
    id?: number | null;
    severity: IssueSeverity;
    category: IssueCategory;
    title: string;
    description: string;
    epoch_index?: number | null;
    layer_id?: string | null;
    metric_key?: string | null;
    metric_value?: unknown | null;
    suggestion?: string;
};

export type IssueSeverity = 'critical' | 'warning' | 'info';

/**
 * All issues pointing to a specific layer, scored for ranking.
 */
export type LayerHighlight = {
    layer_id: string;
    layer_type?: string | null;
    severity_score: number;
    issues: Array<IssueOut>;
};

export type LogKind = 'console' | 'error';

export type Model = {
    id?: number | null;
    session_id: number;
    architecture?: {
        [key: string]: unknown;
    };
    hyperparameters?: {
        [key: string]: unknown;
    };
};

export type ModelCreateRequest = {
    architecture: {
        [key: string]: unknown;
    };
    hyperparameters: {
        [key: string]: unknown;
    };
};

export type Project = {
    id?: number | null;
    name: string;
    created_at?: string;
};

export type ProjectCreate = {
    name: string;
};

export type ProjectTrendOut = {
    project_id: number;
    sessions: Array<SessionTrendItem>;
    improving?: boolean | null;
};

export type ProjectWithStatus = {
    id?: number | null;
    name: string;
    created_at?: string;
    status?: SessionStatus | null;
};

export type SessionLog = {
    id?: number | null;
    session_id: number;
    ts: string;
    level: string;
    msg: string;
    module?: string;
    lineno?: number;
    kind?: LogKind;
};

export type SessionLogCreate = {
    ts: string;
    level: string;
    msg: string;
    module?: string;
    lineno?: number;
    kind?: 'console' | 'error';
};

export type SessionStatus = 'running' | 'completed' | 'failed' | 'pending' | 'analyzing';

export type SessionTrendItem = {
    session_id: number;
    run_id: string;
    run_name: string;
    started_at: string;
    health_score?: number | null;
    final_train_loss?: number | null;
    final_val_loss?: number | null;
    val_acc?: number | null;
    issue_count?: number | null;
};

/**
 * GreenAI sustainability metrics for a diagnostic run.
 */
export type SustainabilityInsight = {
    optimal_stop_epoch?: number | null;
    wasted_epochs?: number | null;
    wasted_compute_pct?: number | null;
    wasted_duration_seconds?: number | null;
    parameter_efficiency_score?: number | null;
    total_training_duration_seconds?: number | null;
    total_samples_processed?: number | null;
    dead_layers?: Array<string>;
    vanishing_gradient_layers?: Array<string>;
    frozen_output_layers?: Array<string>;
    redundant_layer_pairs?: Array<{
        [key: string]: unknown;
    }>;
    sustainability_issue_count?: number;
    total_co2_kg?: number | null;
    total_energy_kwh?: number | null;
    co2_per_epoch_avg_kg?: number | null;
    co2_per_1k_samples_kg?: number | null;
    avg_power_draw_watts?: number | null;
    wasted_co2_kg?: number | null;
};

export type TrainSession = {
    id?: number | null;
    project_id: number;
    run_id: string;
    run_name: string;
    started_at: string;
    ended_at?: string | null;
    device?: string;
    cuda_available?: boolean;
    pytorch_version?: string;
    config?: {
        [key: string]: unknown;
    } | null;
    summary?: {
        [key: string]: unknown;
    } | null;
    status?: SessionStatus;
};

export type TrainSessionCreate = {
    run_id: string;
    run_name: string;
    started_at: string;
    device: string;
    cuda_available: boolean;
    pytorch_version: string;
    config: {
        [key: string]: unknown;
    };
    status?: SessionStatus;
};

export type TrainSessionUpdate = {
    ended_at?: string | null;
    summary?: {
        [key: string]: unknown;
    } | null;
    status?: SessionStatus | null;
};

export type TrainStep = {
    id?: number | null;
    session_id: number;
    step_index: number;
    timestamp: string;
    duration_seconds: number;
    loss?: {
        [key: string]: unknown;
    };
    throughput?: {
        [key: string]: unknown;
    };
    profiler?: {
        [key: string]: unknown;
    };
    memory?: {
        [key: string]: unknown;
    };
    system?: {
        [key: string]: unknown;
    };
    layer_health?: {
        [key: string]: unknown;
    } | null;
    sustainability?: {
        [key: string]: unknown;
    } | null;
    carbon_emissions?: {
        [key: string]: unknown;
    } | null;
    log_counts?: {
        [key: string]: unknown;
    } | null;
};

export type TrainStepCreate = {
    step_index: number;
    timestamp: string;
    duration_seconds: number;
    loss: {
        [key: string]: unknown;
    };
    throughput: {
        [key: string]: unknown;
    };
    profiler: {
        [key: string]: unknown;
    };
    memory: {
        [key: string]: unknown;
    };
    system: {
        [key: string]: unknown;
    };
    layer_health?: {
        [key: string]: unknown;
    } | null;
    sustainability?: {
        [key: string]: unknown;
    } | null;
    carbon_emissions?: {
        [key: string]: unknown;
    } | null;
    log_counts?: {
        [key: string]: unknown;
    } | null;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type GetProjectsProjectsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/projects/';
};

export type GetProjectsProjectsGetErrors = {
    /**
     * Not found
     */
    404: unknown;
};

export type GetProjectsProjectsGetResponses = {
    /**
     * Successful Response
     */
    200: Array<ProjectWithStatus>;
};

export type GetProjectsProjectsGetResponse = GetProjectsProjectsGetResponses[keyof GetProjectsProjectsGetResponses];

export type CreateProjectProjectsPostData = {
    body: ProjectCreate;
    path?: never;
    query?: never;
    url: '/projects/';
};

export type CreateProjectProjectsPostErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateProjectProjectsPostError = CreateProjectProjectsPostErrors[keyof CreateProjectProjectsPostErrors];

export type CreateProjectProjectsPostResponses = {
    /**
     * Successful Response
     */
    200: Project;
};

export type CreateProjectProjectsPostResponse = CreateProjectProjectsPostResponses[keyof CreateProjectProjectsPostResponses];

export type GetProjectProjectsProjectIdGetData = {
    body?: never;
    path: {
        project_id: number;
    };
    query?: never;
    url: '/projects/{project_id}';
};

export type GetProjectProjectsProjectIdGetErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetProjectProjectsProjectIdGetError = GetProjectProjectsProjectIdGetErrors[keyof GetProjectProjectsProjectIdGetErrors];

export type GetProjectProjectsProjectIdGetResponses = {
    /**
     * Successful Response
     */
    200: Project;
};

export type GetProjectProjectsProjectIdGetResponse = GetProjectProjectsProjectIdGetResponses[keyof GetProjectProjectsProjectIdGetResponses];

export type GetTrainSessionsSessionsProjectProjectIdGetData = {
    body?: never;
    path: {
        project_id: number;
    };
    query?: never;
    url: '/sessions/project/{project_id}';
};

export type GetTrainSessionsSessionsProjectProjectIdGetErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTrainSessionsSessionsProjectProjectIdGetError = GetTrainSessionsSessionsProjectProjectIdGetErrors[keyof GetTrainSessionsSessionsProjectProjectIdGetErrors];

export type GetTrainSessionsSessionsProjectProjectIdGetResponses = {
    /**
     * Successful Response
     */
    200: Array<TrainSession>;
};

export type GetTrainSessionsSessionsProjectProjectIdGetResponse = GetTrainSessionsSessionsProjectProjectIdGetResponses[keyof GetTrainSessionsSessionsProjectProjectIdGetResponses];

export type CreateTrainSessionSessionsProjectProjectIdPostData = {
    body: TrainSessionCreate;
    path: {
        project_id: number;
    };
    query?: never;
    url: '/sessions/project/{project_id}';
};

export type CreateTrainSessionSessionsProjectProjectIdPostErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTrainSessionSessionsProjectProjectIdPostError = CreateTrainSessionSessionsProjectProjectIdPostErrors[keyof CreateTrainSessionSessionsProjectProjectIdPostErrors];

export type CreateTrainSessionSessionsProjectProjectIdPostResponses = {
    /**
     * Successful Response
     */
    200: TrainSession;
};

export type CreateTrainSessionSessionsProjectProjectIdPostResponse = CreateTrainSessionSessionsProjectProjectIdPostResponses[keyof CreateTrainSessionSessionsProjectProjectIdPostResponses];

export type GetTrainSessionSessionsSessionIdGetData = {
    body?: never;
    path: {
        session_id: number;
    };
    query?: never;
    url: '/sessions/{session_id}';
};

export type GetTrainSessionSessionsSessionIdGetErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTrainSessionSessionsSessionIdGetError = GetTrainSessionSessionsSessionIdGetErrors[keyof GetTrainSessionSessionsSessionIdGetErrors];

export type GetTrainSessionSessionsSessionIdGetResponses = {
    /**
     * Successful Response
     */
    200: TrainSession;
};

export type GetTrainSessionSessionsSessionIdGetResponse = GetTrainSessionSessionsSessionIdGetResponses[keyof GetTrainSessionSessionsSessionIdGetResponses];

export type UpdateTrainSessionSessionsSessionIdPatchData = {
    body: TrainSessionUpdate;
    path: {
        session_id: number;
    };
    query?: never;
    url: '/sessions/{session_id}';
};

export type UpdateTrainSessionSessionsSessionIdPatchErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateTrainSessionSessionsSessionIdPatchError = UpdateTrainSessionSessionsSessionIdPatchErrors[keyof UpdateTrainSessionSessionsSessionIdPatchErrors];

export type UpdateTrainSessionSessionsSessionIdPatchResponses = {
    /**
     * Successful Response
     */
    200: TrainSession;
};

export type UpdateTrainSessionSessionsSessionIdPatchResponse = UpdateTrainSessionSessionsSessionIdPatchResponses[keyof UpdateTrainSessionSessionsSessionIdPatchResponses];

export type GetTrainSessionStatusSessionsSessionIdStatusGetData = {
    body?: never;
    path: {
        session_id: number;
    };
    query?: never;
    url: '/sessions/{session_id}/status';
};

export type GetTrainSessionStatusSessionsSessionIdStatusGetErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTrainSessionStatusSessionsSessionIdStatusGetError = GetTrainSessionStatusSessionsSessionIdStatusGetErrors[keyof GetTrainSessionStatusSessionsSessionIdStatusGetErrors];

export type GetTrainSessionStatusSessionsSessionIdStatusGetResponses = {
    /**
     * Successful Response
     */
    200: SessionStatus;
};

export type GetTrainSessionStatusSessionsSessionIdStatusGetResponse = GetTrainSessionStatusSessionsSessionIdStatusGetResponses[keyof GetTrainSessionStatusSessionsSessionIdStatusGetResponses];

export type GetModelSessionsSessionIdModelGetData = {
    body?: never;
    path: {
        session_id: number;
    };
    query?: never;
    url: '/sessions/{session_id}/model';
};

export type GetModelSessionsSessionIdModelGetErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetModelSessionsSessionIdModelGetError = GetModelSessionsSessionIdModelGetErrors[keyof GetModelSessionsSessionIdModelGetErrors];

export type GetModelSessionsSessionIdModelGetResponses = {
    /**
     * Successful Response
     */
    200: Model;
};

export type GetModelSessionsSessionIdModelGetResponse = GetModelSessionsSessionIdModelGetResponses[keyof GetModelSessionsSessionIdModelGetResponses];

export type RegisterModelSessionsSessionIdModelPostData = {
    body: ModelCreateRequest;
    path: {
        session_id: number;
    };
    query?: never;
    url: '/sessions/{session_id}/model';
};

export type RegisterModelSessionsSessionIdModelPostErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterModelSessionsSessionIdModelPostError = RegisterModelSessionsSessionIdModelPostErrors[keyof RegisterModelSessionsSessionIdModelPostErrors];

export type RegisterModelSessionsSessionIdModelPostResponses = {
    /**
     * Successful Response
     */
    200: Model;
};

export type RegisterModelSessionsSessionIdModelPostResponse = RegisterModelSessionsSessionIdModelPostResponses[keyof RegisterModelSessionsSessionIdModelPostResponses];

export type GetStepsSessionsSessionIdStepGetData = {
    body?: never;
    path: {
        session_id: number;
    };
    query?: never;
    url: '/sessions/{session_id}/step';
};

export type GetStepsSessionsSessionIdStepGetErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetStepsSessionsSessionIdStepGetError = GetStepsSessionsSessionIdStepGetErrors[keyof GetStepsSessionsSessionIdStepGetErrors];

export type GetStepsSessionsSessionIdStepGetResponses = {
    /**
     * Successful Response
     */
    200: Array<TrainStep>;
};

export type GetStepsSessionsSessionIdStepGetResponse = GetStepsSessionsSessionIdStepGetResponses[keyof GetStepsSessionsSessionIdStepGetResponses];

export type RegisterStepSessionsSessionIdStepPostData = {
    body: TrainStepCreate;
    path: {
        session_id: number;
    };
    query?: never;
    url: '/sessions/{session_id}/step';
};

export type RegisterStepSessionsSessionIdStepPostErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterStepSessionsSessionIdStepPostError = RegisterStepSessionsSessionIdStepPostErrors[keyof RegisterStepSessionsSessionIdStepPostErrors];

export type RegisterStepSessionsSessionIdStepPostResponses = {
    /**
     * Successful Response
     */
    200: TrainStep;
};

export type RegisterStepSessionsSessionIdStepPostResponse = RegisterStepSessionsSessionIdStepPostResponses[keyof RegisterStepSessionsSessionIdStepPostResponses];

export type CreateSessionLogSessionsSessionIdLogPostData = {
    body: SessionLogCreate;
    path: {
        session_id: number;
    };
    query?: never;
    url: '/sessions/{session_id}/log';
};

export type CreateSessionLogSessionsSessionIdLogPostErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateSessionLogSessionsSessionIdLogPostError = CreateSessionLogSessionsSessionIdLogPostErrors[keyof CreateSessionLogSessionsSessionIdLogPostErrors];

export type CreateSessionLogSessionsSessionIdLogPostResponses = {
    /**
     * Successful Response
     */
    201: SessionLog;
};

export type CreateSessionLogSessionsSessionIdLogPostResponse = CreateSessionLogSessionsSessionIdLogPostResponses[keyof CreateSessionLogSessionsSessionIdLogPostResponses];

export type GetSessionLogsSessionsSessionIdLogsGetData = {
    body?: never;
    path: {
        session_id: number;
    };
    query?: never;
    url: '/sessions/{session_id}/logs';
};

export type GetSessionLogsSessionsSessionIdLogsGetErrors = {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSessionLogsSessionsSessionIdLogsGetError = GetSessionLogsSessionsSessionIdLogsGetErrors[keyof GetSessionLogsSessionsSessionIdLogsGetErrors];

export type GetSessionLogsSessionsSessionIdLogsGetResponses = {
    /**
     * Successful Response
     */
    200: Array<SessionLog>;
};

export type GetSessionLogsSessionsSessionIdLogsGetResponse = GetSessionLogsSessionsSessionIdLogsGetResponses[keyof GetSessionLogsSessionsSessionIdLogsGetResponses];

export type RunSessionDiagnosticsDiagnosticsSessionsSessionIdRunPostData = {
    body?: never;
    path: {
        session_id: number;
    };
    query?: never;
    url: '/diagnostics/sessions/{session_id}/run';
};

export type RunSessionDiagnosticsDiagnosticsSessionsSessionIdRunPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RunSessionDiagnosticsDiagnosticsSessionsSessionIdRunPostError = RunSessionDiagnosticsDiagnosticsSessionsSessionIdRunPostErrors[keyof RunSessionDiagnosticsDiagnosticsSessionsSessionIdRunPostErrors];

export type RunSessionDiagnosticsDiagnosticsSessionsSessionIdRunPostResponses = {
    /**
     * Successful Response
     */
    200: DiagnosticRunOut;
};

export type RunSessionDiagnosticsDiagnosticsSessionsSessionIdRunPostResponse = RunSessionDiagnosticsDiagnosticsSessionsSessionIdRunPostResponses[keyof RunSessionDiagnosticsDiagnosticsSessionsSessionIdRunPostResponses];

export type ListSessionDiagnosticRunsDiagnosticsSessionsSessionIdGetData = {
    body?: never;
    path: {
        session_id: number;
    };
    query?: never;
    url: '/diagnostics/sessions/{session_id}';
};

export type ListSessionDiagnosticRunsDiagnosticsSessionsSessionIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListSessionDiagnosticRunsDiagnosticsSessionsSessionIdGetError = ListSessionDiagnosticRunsDiagnosticsSessionsSessionIdGetErrors[keyof ListSessionDiagnosticRunsDiagnosticsSessionsSessionIdGetErrors];

export type ListSessionDiagnosticRunsDiagnosticsSessionsSessionIdGetResponses = {
    /**
     * Successful Response
     */
    200: Array<DiagnosticRunSummary>;
};

export type ListSessionDiagnosticRunsDiagnosticsSessionsSessionIdGetResponse = ListSessionDiagnosticRunsDiagnosticsSessionsSessionIdGetResponses[keyof ListSessionDiagnosticRunsDiagnosticsSessionsSessionIdGetResponses];

export type GetDiagnosticRunDiagnosticsRunsRunIdGetData = {
    body?: never;
    path: {
        run_id: number;
    };
    query?: never;
    url: '/diagnostics/runs/{run_id}';
};

export type GetDiagnosticRunDiagnosticsRunsRunIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDiagnosticRunDiagnosticsRunsRunIdGetError = GetDiagnosticRunDiagnosticsRunsRunIdGetErrors[keyof GetDiagnosticRunDiagnosticsRunsRunIdGetErrors];

export type GetDiagnosticRunDiagnosticsRunsRunIdGetResponses = {
    /**
     * Successful Response
     */
    200: DiagnosticRunOut;
};

export type GetDiagnosticRunDiagnosticsRunsRunIdGetResponse = GetDiagnosticRunDiagnosticsRunsRunIdGetResponses[keyof GetDiagnosticRunDiagnosticsRunsRunIdGetResponses];

export type GetSessionHealthDiagnosticsSessionsSessionIdHealthGetData = {
    body?: never;
    path: {
        session_id: number;
    };
    query?: never;
    url: '/diagnostics/sessions/{session_id}/health';
};

export type GetSessionHealthDiagnosticsSessionsSessionIdHealthGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSessionHealthDiagnosticsSessionsSessionIdHealthGetError = GetSessionHealthDiagnosticsSessionsSessionIdHealthGetErrors[keyof GetSessionHealthDiagnosticsSessionsSessionIdHealthGetErrors];

export type GetSessionHealthDiagnosticsSessionsSessionIdHealthGetResponses = {
    /**
     * Successful Response
     */
    200: HealthOut;
};

export type GetSessionHealthDiagnosticsSessionsSessionIdHealthGetResponse = GetSessionHealthDiagnosticsSessionsSessionIdHealthGetResponses[keyof GetSessionHealthDiagnosticsSessionsSessionIdHealthGetResponses];

export type GetProjectTrendDiagnosticsProjectsProjectIdTrendGetData = {
    body?: never;
    path: {
        project_id: number;
    };
    query?: never;
    url: '/diagnostics/projects/{project_id}/trend';
};

export type GetProjectTrendDiagnosticsProjectsProjectIdTrendGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetProjectTrendDiagnosticsProjectsProjectIdTrendGetError = GetProjectTrendDiagnosticsProjectsProjectIdTrendGetErrors[keyof GetProjectTrendDiagnosticsProjectsProjectIdTrendGetErrors];

export type GetProjectTrendDiagnosticsProjectsProjectIdTrendGetResponses = {
    /**
     * Successful Response
     */
    200: ProjectTrendOut;
};

export type GetProjectTrendDiagnosticsProjectsProjectIdTrendGetResponse = GetProjectTrendDiagnosticsProjectsProjectIdTrendGetResponses[keyof GetProjectTrendDiagnosticsProjectsProjectIdTrendGetResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};